export const Arabic: any = {
  dir: "rtl",
  lang: "English",
  font: "cairoFont",
  navFloat: "",
  arabicClass: "arabic",
  rowReverse: "row-reverse",
  menuStyle: "arabicMenu",
  menuCloseStyle: "arabicCloseButton",
  textAlign: "text-right",
  textAlignReverse: "text-left",
  FlexAlignItems: "align-items-end",

  flexDIr: "flex-row-reverse",
  copyRights1: "كل الحقوق محفوظة |",
  terms: "شروط",
  policy: "احكام",
  logout: "خروج",
  modal: {
    confirm: "هل انت متأكد انك تريد المتابعة؟",
    confirm_change_password: "هل أنت متأكد أنك تريد تغيير كلمة مرور هذا الحساب؟",
    confirm_change_email: "هل أنت متأكد أنك تريد تغيير هذا البريد الإلكتروني؟",
    confirm_create_email: "هل أنت متأكد أنك تريد إنشاء هذا البريد الإلكتروني؟",
    confirm_cancel_operation: "هل أنت متأكد أنك تريد إلغاء هذه العملية؟",
    serverError: "حدث خطأ داخلي في الخادم",
    invalidEndDate: "يجب أن يكون تاريخ الانتهاء بعد تاريخ البدء",
    confirmationTitle: {
      changePassword: "تغيير كلمة المرور",
      changeEmail: "تغيير البريد الالكتروني",
      createEmail: "انشاء بريد الكتروني",
      cancelOperation: "إلغاء العملية",
    },
    success: "تمت بنجاح",

  },
  invalid: {
    invalidEmail: "البريد الالكتروني غير صحيح",
    requiredEmail: "ادخل البريد الالكتروني",
    requiredUserName: "ادخل الاسم",
    requiredPassword: "ادخل الرقم السري",
    InvalidPassword: "الرقم السري غير صحيح",
    InvalidPercentage: "النسبة غير صحيحة",
    invalidLogin: "تأكد من البيانات",
    invalidRegister: "خطأ في تقديم الطلب ، يرجى المحاولة مرة أخرى",
    loginRedirect: "سيتم إعادة توجيهك بعد قليل",
    requiredField: "من فضلك ادخل البيانات"
  },
  login: {
    wlc: "مرحبا بك في",
    forgetPassword: "نسيت كلمة المرور؟ ",
    desc: "نسهل على الجميع الاستثمار في الخدمات المصرفية",
    login: "الدخول",
    donHaveAcc: "ليس لديك حساب ،",
    createAcc: "إنشاء حساب",
    QuestionMark: "؟"

  },
  placeholder: {
    email: "البريد الالكتروني",
    name: "الاسم",
    password: "الرقم السري",
    FirstName: "الاسم الاول",
    LastName: "الاسم الاخير",
    ConfirmPassword: "تأكيد كلمة المرور",
    PhoneNumber: "رقم الهاتف",
    search: "بحث",
    return: "الرجوع",
    authorization: "الصلاحية",
  },
  register: {
    register: "تسجيل ",
    back: "رجوع",
    next: "التالي",
    haveAcc: "لديك حساب ،",

  },

  headers: {

    UserManagement: "ادارة المستخدمين",
    Description: "الوصف",
    Title: 'العنوان',
    Status: "الحالة",
    Type: "النوع",
    Actions: "اجراءات",
    entries: "اجمالي ادخالات ",
    of: "من",
    to: "الي",
    Details: "تفاصيل",
    Department: "القسم",
    Employees: "الموظف",
    Users: "مستخدمين",
    Note: "ملحوظة",

  },
  actions: {
    Add: "اضافة",
    Edit: "تعديل",
    Delete: "حذف",
    Submit: "تأكيد",
    Done: "تم",
    Save:"حفظ",
    Cancel: "اغلاق",
    Select: "اختر",
    Review: "مراجعة",
    Next: "التالي",
    Previous: "السابق",
    dropdownLabelName: "nameAR",
    dropdownLabelHeader: "headerAR",
    SearchByTitle: "بحث ",
    NoRecordsFound: "لا يوجد بيانات",
    RefreshRFQ: " RFQ تحديث",
    CreateSourcingEvent: " انشاء مناقصة",
    resumeCreation: "استمرار الانشاء",
    Upload: "تنزيل",
    View: "عرض",
    Validate: "تحقق",
    launch: "إطلاق",
    discard: 'انهاء',
    reject: 'رفض',

  },
  dashboard: {
    Dashboard: "لوحة المتابعة و التقارير",
    NumberOfSuppliers: "عدد الموردين",
    NumberOfSellers: "عدد البائعين",
    NumberOfTenders: "عدد المناقصات",
    NumberOfMembers: "عدد من أعضاء",
    TIMEREMAINING: "الوقت المتبقي",
    Visitors: " زوار ",
    Sales: "مبيعات",
    ViewReport: "عرض التقرير",
    VisitorsOverTime: "الزوار بمرور الوقت",
    SalesOverTime: "المبيعات بمرور الوقت",
    SinceLastMonth: "منذ اخر شهر",

  },
  TODO: {
    title: "قائمة المهام",
    Completed: "تمت",
    InProgress: "في تقدم",
    GoToTask: "انتقل إلى المهمة",
    Tasks: "المهام",

  },
  
  generalResponse: {
    passwordChanged: "تم تغيير الرقم السرى",
    userActivated: "تم تنشيط المستخدم",
    userDeactivated: "تم إلغاء تنشيط المستخدم",
    emailChanged: "تم تغيير البريد الإلكتروني",
    emailCreated: "تم إنشاء البريد الإلكتروني",
    sourcingEvent_Created: "تم إنشاء حدث تحديد المصدر بنجاح",
    refreshed: "تم التحدبث",
  },
  connection:{
    connected: "متصل بالإنترنت",
    disconnected: "انقطع الاتصال بالإنترنت"
  },
 

}
