export const English: any = {
  dir: "ltr",
  lang: "العربية",
  arabicClass: "",
  benefits: "Benefits & Features",
  textAlign: "text-left",
  textAlignReverse: "text-right",
  FlexAlignItems: "align-items-start",
  rowReverse: "",
  menuStyle: "",
  menuCloseStyle: "",
  navFloat: "float-right",
  quickLinks: "Quick Links",
  followUs: "Follow Us",
  copyRights1: "Copyright &copy; 2021, All rights reserved |",
  terms: "Terms",
  policy: "Policy",
  logout: "Logout",

  modal: {
    confirm: "Are you sure you want to proceed?",
    confirm_change_password: "Are you sure you want to change this account's password?",
    confirm_change_email: "Are you sure you want to change this email?",
    confirm_create_email: "Are you sure you want to create this email?",
    confirm_cancel_operation: "Are you sure you want to cancel this process?",
    serverError: "Internal server error occured",
    invalidEndDate: "End date must be after start date",
    confirmationTitle: {
      changePassword: "Change Password",
      changeEmail: "Change Email",
      createEmail: "Create Email",
      cancelOperation: "Cancel operation",
    },
    success: "Done successfully",

  },
  invalid: {
    invalidEmail: "Invalid e-mail ",
    requiredEmail: "E-mail required ",
    requiredUserName: "Username required",
    requiredPassword: "Password required",
    InvalidPassword: "Invalid password",
    invalidLogin: "Enter valid email and password",
    invalidRegister: "Error submitting request, please try again shortly.",
    loginRedirect: "You will be redirected shortly",
    requiredField: "Required field",
    InvalidPercentage: "Invalid Percentage",

  },
  login: {
    wlc: "Welcome to",
    forgetPassword: " Forget Password? ",
    desc: "",
    login: "Login",
    donHaveAcc: "Don't have an account,",
    createAcc: "Create Account",
    QuestionMark: "?"
  },
  placeholder: { //general placeholders
    email: "Email",
    password: "Password",
    name: "Name",
    FirstName: "First Name",
    LastName: "Last Name",
    ConfirmPassword: "Confirm Password",
    PhoneNumber: "Phone Number",
    search: "Search",
    return: "Return",
    authorization: "Authorization",
  },
  register: {
    register: "Register",
    back: "Back",
    next: "Next",
    haveAcc: "have an account,",

  },


  headers: {

    UserManagement: "User Management",
    Description: "Description",
    Title: "Title",
    authorizationManagement: "Authorization Management",
    RFQCollectiveNumber: "RFQ Collective Number	",
    Status: "Status",
    Type: "Type",
    Actions: "Actions",
    entries: "entries",
    of: "of",
    to: "to",
    Details: "Details",
    Department: "Department",
    Employees: "Employee",
    Users: "Users",
    Note: "Note",


  },
  actions: {
    Add: "Add",
    Edit: "Edit",
    Delete: "Delete",
    Submit: "Confirm",
    Done: "Done",

    Cancel: "Cancel",
    Select: "Select",
    Review: "Review",
    Next: "Next",
    Save: "Save",
    Previous: "Previous",
    dropdownLabelName: "name",
    dropdownLabelHeader: "header",
    SearchByTitle: "Search",
    NoRecordsFound: "No records found",
    RefreshRFQ: "Refresh RFQ",
    CreateSourcingEvent: "Create Tender ",
    resumeCreation: "Resume Creation",
    Upload: "Upload",
    View: "View",
    Validate: "Validate",
    launch: "Launch",
    discard: 'Discard',
    reject: 'Reject',

  },
  dashboard: {
    Dashboard: "Dashboard",
    NumberOfSuppliers: "Number Of Suppliers",
    NumberOfSellers: "Number Of Sellers",
    NumberOfTenders: "Number Of Tenders",
    NumberOfMembers: "Number Of Members",
    TIMEREMAINING: "TIME REMAINING",
    Visitors: "Visitors",
    Sales: "Sales",
    ViewReport: "View Report",
    VisitorsOverTime: "Visitors Over Time",
    SalesOverTime: "Sales Over Time",
    SinceLastMonth: "Since last month",
  },
  TODO: {
    title: "To Do Tasks",
    Completed: "Completed",
    InProgress: "In progress",
    GoToTask: "Go to task",
    Tasks: "To Do",
  },

  generalResponse: {
    passwordChanged: "Password changed",
    userActivated: "User Activated",
    userDeactivated: "User Deactivated",
    emailChanged: "Email changed",
    emailCreated: "Email created",
    sourcingEvent_Created: "Sourcing Event created successfully",
    refreshed: "Refreshed",
  },
  connection: {
    connected: "Internet Connection Established",
    disconnected: "Internet Disconnected"
  },
  

}
